version: '3'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:80"
    volumes:
      - portrainer_data:/var/lib/docker/volumes/fast-api_portrainer_data/_data
    networks:
      - my_network

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "8080:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/hcpdocker/data/portainer_data:/data
    networks:
      - 80f724f9b1554a3d9e591e85c35f2b49350b709db111966a1dd58544c3f6e2e6
 

volumes:
  portrainer_data:
    driver: local

networks:
  my_network:
    driver: bridge
