version: '3'

services:
  nginx:
    context: .
    image: nginx
    dockerfile: ./requirements/nginx/.
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/html
    networks:
     - inception 
    restart: always

  mariadb:
    container: mariadb
    image: mariadb
    dockerfile: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    environment:
     - .env
    networks:
     - inception

  wordpress:
    container: wordpress
    image: wordpress
    dockerfile: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volume:
      - wordpress:/var/www/html
    environment:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wordpress:
  mariadb:

networks:
  inception:
    driver: bridge
