version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/wordpress
    networks:
     - inception
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
     - .env
    networks:
     - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
volumes:
    wordpress:
      name: wordpress
      driver: local
      driver_opts:
       type: 'none'
       o: 'bind'
       device: '$HOME/data/wordpress'
    mariadb:
      name: mariadb
      driver: local
      driver_opts:
       type: 'none'
       o: 'bind'
       device: '$HOME/data/mariadb' 

networks:
  inception:
    driver: bridge
