version: '3'

services:
  nginx:
    image: nginx
    build: ./requirements/nginx/.
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/html
    networks:
     - inception 
    restart: always

  mariadb:
    image: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    environment:
     - .env
    networks:
     - inception

  wordpress:
    image: wordpress
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volume:
      - wordpress:/var/www/html
    environment:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wordpress:
  mariadb:

networks:
  inception:
    driver: bridge
