version: '3'

services:
  nginx:
    context: .
    dockerfile: ./nginx/Dockerfile
    ports:
     - "443:443"
    volumes:
     - 


  db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
      - ./.env
  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       - ./.env
